trigger:
- none

variables:
- group: vargroup01

resources:
  repositories:
    - repository: templates      # alias que vas a usar en el template
      type: github               # porque está en GitHub
      name: bernandez88/templates # owner/repo en GitHub
      ref: refs/heads/main       # rama donde está tu template
      endpoint: GitHub-Connection # nombre del Service Connection a GitHub

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: functions/template-trigger.yml@templates
